# Generated by Django 5.2.11 on 2026-03-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('video', models.FileField(upload_to='videos/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
