# Generated by Django 5.2.11 on 2026-03-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('weapon', 'Weapon Detection'), ('violence', 'Violence Detection')], max_length=20),
        ),
    ]
